site_name: Splunk TA for SAP LogServ
site_author: Splunk
site_url: "https://splunk.github.io/splunk-sap-logserv/"
edit_uri: "tree/main/docs/"
remote_branch: gh-pages

repo_name: Splunk TA for SAP LogServ
repo_url: "https://github.com/splunk/splunk-sap-logserv"

# site_dir: site

markdown_extensions:
  - toc:
      permalink: True
  - smarty
  - fenced_code
  - sane_lists
  - codehilite
  - pymdownx.superfences:
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  

theme:
  name: "material"
  custom_dir: docs/theme_overrides
  logo: "static/splunk-logo.png"
  favicon: "static/splunk.png"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    #- navigation.indexes
    - navigation.instant.preview


extra_css:
  - css/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: true
            filters: ["!^_"]
            show_source: true
  - autorefs
  - print-site  # should be at the end

nav:
- Overview:
    - Release Notes: 'content/overview/release-notes.md'
    - About the Add-on: 'index.md'
    - Installation and Setup Overview: 'content/overview/install-setup.md'
    - Sourcetype mapping: 'content/overview/ta_mapping.md'
- Installation and Setup:
    - Prerequisites: 'content/install-setup/prerequisites.md'
    - Installing the TA: 'content/install-setup/install-ta.md'
    - Configuring Filters: 'content/install-setup/configure-filters.md'
    - Setup Walkthroughs Overview: 'content/install-setup/setup-walkthroughs.md'
    - AWS Setup Walkthroughs:
        - AWS Remote S3 Connect Setup Walkthrough: 'content/install-setup/aws-remote-s3-connect-walkthrough.md'
        - AWS Remote S3 Filter Setup Walkthrough: 'content/install-setup/aws-remote-s3-filter-walkthrough.md'    
        - AWS Remote S3 Copy Setup Walkthrough: 'content/install-setup/aws-remote-s3-copy-walkthrough.md'
    - AWS Setup Migrations:
        - AWS Remote S3 Connect to Filter Migration: 'content/install-setup/aws-remote-s3-connect-to-filter-migration-walkthrough.md'    
#- Developer Reference:
#    - Architecture and Internals: 'content/developer/developer-reference.md'
