[id]
name = splunk_app_sap_logserv
version = 0.0.6

[ui]
is_visible = 1
label = Splunk App for SAP LogServ
supported_themes = light,dark

[launcher]
author = Splunk
description = Dashboards and analytics for SAP LogServ data
version = 0.0.6

[package]
check_for_updates = 0
id = splunk_app_sap_logserv

[install]
is_configured = 0
build = 252

[triggers]
reload.splunk_create = simple
reload.ai_assistant_settings = simple
reload.ai_assistant_acks = simple
reload.correlationsearches = simple
