[shclustering]
conf_replication_include.ai_assistant_acks = true
conf_replication_include.ai_assistant_settings = true
conf_replication_include.correlationsearches = true
conf_replication_include.eventtypes = true
conf_replication_include.macros = true
conf_replication_include.props = true
conf_replication_include.savedsearches = true
conf_replication_include.splunk_create = true
conf_replication_include.tags = true
conf_replication_include.transforms = true
