[launcher]
author = Splunk
description = Dashboards and analytics for SAP LogServ data

[ui]
is_visible = 1
label = Splunk App for SAP LogServ

[package]
id = splunk_app_sap_logserv
check_for_updates = 0

[id]
version = 0.0.4.2
build = 1
