[sap_logserv_logs]
TIME_PREFIX = _time\"\s*:
TIME_FORMAT = %s.%3N
MAX_TIMESTAMP_LOOKAHEAD = 24
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
SHOULD_LINEMERGE = false
TRANSFORMS-01-metadata = extract_host, extract_source, extract_clz
TRANSFORMS-02-srctype_for_nix = set_srctype_for_linux_messages_syslog, set_srctype_for_linux_cron, set_srctype_for_linux_warn, set_srctype_for_linux_sudolog, set_srctype_for_linux_slapd, set_srctype_for_linux_secure, set_srctype_lastlog, set_srctype_who
TRANSFORMS-03-srctype_for_isc = set_srctype_for_isc_bind_query, set_srctype_if_varlognamed_lameservers, set_srctype_if_varlognamed_network, set_srctype_if_varlognamed_notify
TRANSFORMS-04-srctype_for_squid = set_srctype_for_squid_access
TRANSFORMS-05-srctype_for_sap = set_srctype_sap_webdisp_access, set_srctype_hana_audit
TRANSFORMS-06-srctype_for_windows = set_srctype_xmlwineventlog
TRANSFORMS-07-srctype_for_abap = set_srctype_abap_audit, set_srctype_abap_dispatcher, set_srctype_abap_enqueueserver, set_srctype_abap_event, set_srctype_abap_gateway, set_srctype_abap_icm, set_srctype_abap_messageserver, set_srctype_abap_sapstartsrv, set_srctype_abap_workprocess
TRANSFORMS-08-srctype_for_scc_and_hana_trace = set_srctype_scc_audit, set_srctype_scc_http_access, set_srctype_hana_tracelogs
TRANSFORMS-09-srctype_for_sap_services = set_srctype_sap_sapstartsrv, set_srctype_sap_saphostexec, set_srctype_sap_saprouter
TRANSFORMS-50-splunk_solution = logserv_set_splunk_solution
TRANSFORMS-51-cloud_provider = logserv_set_cloud_provider
TRANSFORMS-99-set_raw = set_raw_only

[sap:hana:audit]
TRANSFORMS-transform_log = system_id_metadata, critical_event_metadata, failed_auth_metadata, normalize_user_actions, change_management_extraction, host_from_path
