[sap_logserv_logs]
TIME_PREFIX = _time\"\s*:
TIME_FORMAT = %s.%3N
MAX_TIMESTAMP_LOOKAHEAD = 24
LINE_BREAKER = ([\r\n]+)
SHOULD_LINEMERGE = false
TRANSFORMS-transform_log = extract_host, extract_source, extract_clzdir, extract_clzsubdir, set_srctype_for_linux_messages_syslog, set_srctype_for_syslog, set_srctype_for_linux_secure, set_srctype_for_isc_bind_query, set_srctype_if_varlognamed_lameservers, set_srctype_if_varlognamed_wildcard, set_srctype_if_varlognamed_network, set_srctype_if_varlognamed_notify, set_srctype_for_squid_access, set_raw_only


[syslog]
TRANSFORMS-transform_log = extract_host, extract_source, extract_clzdir, extract_clzsubdir, set_raw_only
EXTRACT-os_user = ^[^\(\n]*\((?P<os_user>\w+)

[linux_messages_syslog]
TRANSFORMS-transform_log = extract_host, extract_source, extract_clzdir, extract_clzsubdir, set_raw_only
EXTRACT-sap_sid = --sid\s+(?<sap_sid>[A-Z0-9_]+)
EXTRACT-sap_cid = --cid\s+(?<sap_cid>[A-Za-z0-9]{3})
EXTRACT-sap_inst = --inst\s*(?<sap_inst>\d+)
EXTRACT-sap_app = --app\s+(?<sap_app>[A-Z0-9_]+)
