[extract_host]
REGEX = "host":"([^"]+)"
FORMAT = host::$1
DEST_KEY = MetaData:Host

[extract_source]
REGEX = "source":"([^"]+)"
FORMAT = source::$1
DEST_KEY = MetaData:Source

[extract_clzdir]
REGEX = "clz_dir":"([^"]+)"
FORMAT = clz_dir::$1
WRITE_META = true

[extract_clzsubdir]
REGEX = "clz_subdir":"([^"]+)"
FORMAT = clz_subdir::$1
WRITE_META = true

[set_srctype_for_linux_messages_syslog]
REGEX = "source":"\/var\/log\/(messages|localmessages)"
FORMAT = sourcetype::linux_messages_syslog
DEST_KEY = MetaData:Sourcetype

[set_srctype_for_syslog]
REGEX = "source":"\/var\/log\/(cron|warn|sudolog|pacemaker\/pacemaker.log)"
FORMAT = sourcetype::syslog
DEST_KEY = MetaData:Sourcetype

[set_srctype_for_linux_secure]
REGEX = "source":"\/var\/log\/(firewall|kernel|sssd\/sssd\.log)"
FORMAT = sourcetype::linux_secure
DEST_KEY = MetaData:Sourcetype

[set_srctype_for_isc_bind_query]
REGEX = "source":"\/var\/lib\/named\/log\/named\/(default\.log|queries\.log)"
FORMAT = sourcetype::isc:bind:query
DEST_KEY = MetaData:Sourcetype

# NO logs available for sourcetypes below YET
[set_srctype_if_varlognamed_lameservers]
REGEX = "source":"\/var\/log\/named\/lame-servers.log"
FORMAT = sourcetype::isc:bind:lameserver
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlognamed_network]
REGEX = "source":"\/var\/log\/named\/network.log"
FORMAT = sourcetype::isc:bind:network
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlognamed_notify]
REGEX = "source":"\/var\/lib\/named\/log\/named\/notify.log"
FORMAT = sourcetype::isc:bind:transfer
DEST_KEY = MetaData:Sourcetype


#TO DO is it necessary?
#[set_srctype_if_varlognamed_wildcard]
#REGEX = "source":"\/var\/log\/named\/ \*\.log"
#FORMAT = sourcetype::isc:bind:query
#DEST_KEY = MetaData:Sourcetype

[set_srctype_for_squid_access]
REGEX = "source":"\/var\/log\/squid\/(access\.log|cache\.log|store\.log)"
FORMAT = sourcetype::squid:access
DEST_KEY = MetaData:Sourcetype

# [set_index_if_varlog_cron]
# REGEX = "source":"\/var\/log\/cron"
# FORMAT = sapls_cron
# DEST_KEY = _MetaData:Index

# [set_index_if_varlog_msgs]
# REGEX = "source":"\/var\/log\/messages"
# FORMAT = sapls_messages
# DEST_KEY = _MetaData:Index

# [set_index_if_varlog_localmsgs]
# REGEX = "source":"\/var\/log\/localmessages"
# FORMAT = sapls_localmessages
# DEST_KEY = _MetaData:Index


[set_raw_only]
REGEX = "_raw":"((?:[^"\\]|\\.)*)
# REGEX = "_raw":"([^"]+)"
FORMAT = $1
DEST_KEY = _raw
