[extract_host]
REGEX = "host":"([^"]+)"
FORMAT = host::$1
DEST_KEY = MetaData:Host

[extract_source]
REGEX = "source":"([^"]+)"
FORMAT = source::$1
DEST_KEY = MetaData:Source

[extract_clzdir]
REGEX = "clz_dir":"([^"]+)"
FORMAT = clz_dir::$1
WRITE_META = true

[extract_clzsubdir]
REGEX = "clz_subdir":"([^"]+)"
FORMAT = clz_subdir::$1
WRITE_META = true

[set_srctype_if_varlog_cron]
REGEX = "source":"\/var\/log\/cron"
FORMAT = sourcetype::syslog
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlog_msgs]
REGEX = "source":"\/var\/log\/messages"
FORMAT = sourcetype::linux_messages_syslog
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlog_localmsgs]
REGEX = "source":"\/var\/log\/localmessages"
FORMAT = sourcetype::linux_messages_syslog
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlog_warn]
REGEX = "source":"\/var\/log\/warn"
FORMAT = sourcetype::syslog
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlog_sudo]
REGEX = "source":"\/var\/log\/sudolog"
FORMAT = sourcetype::syslog
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlog_firewall]
REGEX = "source":"\/var\/log\/firewall"
FORMAT = sourcetype::linux_secure
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlog_kernel]
REGEX = "source":"\/var\/log\/kernel"
FORMAT = sourcetype::linux_secure
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlog_sssd]
REGEX = "source":"\/var\/log\/sssd"
FORMAT = sourcetype::linux_secure
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlibnamed_default]
REGEX = "source":"\/var\/lib\/named\/log\/named\/default.log"
FORMAT = sourcetype::isc:bind:query
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlibnamed_queries]
REGEX = "source":"\/var\/lib\/named\/log\/named\/queries.log"
FORMAT = sourcetype::isc:bind:query
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlogsquid_access]
REGEX = "source":"\/var\/log\/squid\/access.log"
FORMAT = sourcetype::squid:access
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlogsquid_cache]
REGEX = "source":"\/var\/log\/squid\/cache.log"
FORMAT = sourcetype::squid:access
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlogsquid_store]
REGEX = "source":"\/var\/log\/squid\/store.log"
FORMAT = sourcetype::squid:access
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_pacemaker]
REGEX = "clz_subdir":"pacemaker"
FORMAT = sourcetype::syslog
DEST_KEY = MetaData:Sourcetype


# NO logs available for sourcetypes below YET
[set_srctype_if_varlognamed_lameservers]
REGEX = "source":"\/var\/log\/named\/lame-servers.log"
FORMAT = sourcetype::isc:bind:lameserver
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlognamed_wildcard]
REGEX = "source":"\/var\/log\/named\/ \*\.log"
FORMAT = sourcetype::isc:bind:query
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlognamed_network]
REGEX = "source":"\/var\/log\/named\/network.log"
FORMAT = sourcetype::isc:bind:network
DEST_KEY = MetaData:Sourcetype

[set_srctype_if_varlognamed_notify]
REGEX = "source":"\/var\/log\/named\/notify.log"
FORMAT = sourcetype::isc:bind:transfer
DEST_KEY = MetaData:Sourcetype





# [set_index_if_varlog_cron]
# REGEX = "source":"\/var\/log\/cron"
# FORMAT = sapls_cron
# DEST_KEY = _MetaData:Index

# [set_index_if_varlog_msgs]
# REGEX = "source":"\/var\/log\/messages"
# FORMAT = sapls_messages
# DEST_KEY = _MetaData:Index

# [set_index_if_varlog_localmsgs]
# REGEX = "source":"\/var\/log\/localmessages"
# FORMAT = sapls_localmessages
# DEST_KEY = _MetaData:Index


[set_raw_only]
REGEX = "_raw":"((?:[^"\\]|\\.)*)
# REGEX = "_raw":"([^"]+)"
FORMAT = $1
DEST_KEY = _raw
